account/urls.py
from django.urls import path
from . import views

app_name="account"
urlpatterns = [
    path('', views.index, name='index' ),
    path('login/', views.login_user, name='login' ),
    path('register/', views.register_user, name='register' ),
    path('me', views.me, name='me' ),
    path('logout/', views.logout_user, name='logout' ),
]

notenanalyse/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # Landing page and dashboard
    path("", views.index, name="index"),
    path("dashboard", views.dashboard, name="dashboard"),

    # Subjects
    path("subjects", views.subjects, name="subjects"),
    path("subjects/create", views.create_subject, name="create_subject"),
    path("subjects/show", views.show_subject, name="show_subject"),
    path("subjects/delete", views.delete_subjects, name="delete_subject"),

    # Icons
    path("symbols", views.symbols, name="symbols"),
    path("symbols/create", views.create_symbol, name="create_symbol"),
    path("symbols/show", views.create_symbol, name="show_symbol"),
    path("symbols/delete", views.create_symbol, name="delete_symbol"),

    # Account actions
    path('account/', include('account.urls')),
    path('login/', views.login_user, name='login' ),
    path('register/', views.register_user, name='register' ),
    path('logout/', views.logout_user, name='logout' ),
]

notenanalyse/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

class Subject(models.Model):
    id = models.Index
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=256)
    updated_at = models.DateTimeField(blank=True, null=True)
    created_at = models.DateTimeField(datetime.now())

class Symbol(models.Model):
    id = models.Index
    content = models.CharField(max_length=16)

class SchoolYear(models.Model):
    id = models.Index
    name = models.CharField(max_length=64)
    starts_at = models.DateTimeField()
    ends_at = models.DateTimeField(blank=True, null=True)

class User_Subject(models.Model):
    id = models.Index
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    subject_id = models.ForeignKey(Subject, on_delete=models.DO_NOTHING)
    symbol_id = models.ForeignKey(Symbol, on_delete=models.DO_NOTHING)
    school_year_id = models.ForeignKey(SchoolYear, on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(datetime.now())
    updated_at = models.DateTimeField(blank=True, null=True)

notenanalyse/forms.py
from django import forms
from .models import Subject, User_Subject, Symbol


class UserSubjectForm(forms.ModelForm):
    class Meta:
        model = User_Subject
        fields=['symbol_id', 'subject_id', 'school_year_id']
        labels={'symbol_id': 'Fach-Icon',
                'subject_id': 'Fach-Vorlage',
                'school_year_id': 'Gillt für Schuljahr'}

class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject
        fields=['name', 'description']
        labels={'name': 'Bezeichnung', 'description': 'Beschreibung'}

class SymbolForm(forms.ModelForm):
    class Meta:
        model = Symbol
        fields=['content']
        labels={'content': 'Inhalt'}

notenanalyse/views.py
from operator import truediv

from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login, logout, user_login_failed
from django.urls import reverse
from .forms import UserSubjectForm, SymbolForm
from .models import Subject, Symbol, User_Subject


def user_is_logged_in_and_valid(request):
    if request.user and request.user.is_authenticated:
        return True
    else:
        return False


# Create your views here.

def index(request):
    return render(request, 'notenanalyse/index.html')

def login_user(request):
    L_Form = AuthenticationForm()

    if request.method == 'POST':
        L_Form = AuthenticationForm(data=request.POST)

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect(reverse('dashboard'))

    return render(request, 'notenanalyse/login.html', {'L_Form': L_Form})

def logout_user(request):
    logout(request)
    return redirect('index')

def register_user(request):
    R_Form = UserCreationForm()

    if request.method == 'POST':
        # print(request.POST)

        R_Form = UserCreationForm(request.POST)
        if R_Form.is_valid():
            R_Form.save()

            name = R_Form.cleaned_data['username']
            password = R_Form.cleaned_data['password1']
            user = authenticate(request, username=name, password=password)
            if user:
                login(request, user)
                return redirect(reverse('dashboard'))

    return render(request, 'notenanalyse/register.html', {'R_Form': R_Form})

def dashboard(request):
    if user_is_logged_in_and_valid(request): return render(request, './notenanalyse/dashboard.html', {'user': request.user})
    else: return redirect('login')

def subjects(request):
    if user_is_logged_in_and_valid(request):
        subjects_list = Subject.objects.all()
        return render(request, './notenanalyse/subjects/index.html', {'subjects': subjects_list})
    else: return redirect('login')

def show_subject(request):
    if user_is_logged_in_and_valid(request):
        subject_id = request.GET.get('id')
        user_subject = User_Subject.objects.get(pk=subject_id)
        if user_subject:
            return render(request, './notenanalyse/subjects/show.html', {'subject': user_subject})

def delete_subjects(request):
    if user_is_logged_in_and_valid(request):
        subject_id = request.GET.get('id')
        if subject_id:
            user_subject = User_Subject.objects.filter(id=subject_id).get()
            if user_subject.user_id == request.user.id:
                user_subject.delete()
                User_Subject.save()
        return redirect('subjects')


def create_subject(request):
    if request.user:
        subject_form = UserSubjectForm()
        if request.user.is_authenticated: return render(request, './notenanalyse/subjects/create.html', {'form': subject_form})
        else: return redirect('login')
    return redirect('login')

def symbols(request):
    if request.user:
        symbol_list = Symbol.objects.all()
        if request.user.is_authenticated: return render(request, './notenanalyse/icons/index.html', {'symbols': symbol_list})
        else: return redirect('login')
    return redirect('login')

def create_symbol(request):
    if request.user and request.user.is_authenticated:

        symbol_form = SymbolForm()

        if request.method == 'POST':
            symbol_form = SymbolForm(request.POST)
            if symbol_form.is_valid():
                symbol_form.save()
                return render(request, './notenanalyse/icons/index.html', {'form': symbol_form})
        else:
            return render(request, './notenanalyse/icons/create.html', {'form': symbol_form})
    return redirect('login')

templates/notenanalyse/base.html
<!DOCTYPE html>
<html lang="de" class="light">
    <head>
        <meta charset="UTF-8">
        <title>Notenanalyse - Hallo!</title>

        {% load bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}

        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/page.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/colors/light.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body id="body">
        <nav class="navbar-expand-lg navbar always-on-top w-full">
            <div class="container-fluid">
                <div class="w-full flex flex-wrap align-center space-between">
                    <a class="navbar-brand" href="#">
                        <img src="../../static/images/logo.png" alt="Notenanalyse" height="48px" />
                    </a>

                    <!-- User account controls -->
                    <div>
                        {% if user.is_authenticated %}
                            <!-- if user is logged in -->
                            <a href="{% url 'dashboard' %}" class="outlined-button mr-4">
                                <img src="../../static/images/ic_person_24dp.svg" class="desktop-hidden" />
                                <span class="mobile-hidden">Mein Account</span>
                            </a>
                            <a href="{% url 'logout' %}" class="button mr-4">
                                <img src="../../static/images/ic_logout_24dp.svg" class="desktop-hidden" />
                                <span class="mobile-hidden">Abmelden</span>
                            </a>
                        {% else %}
                            <!-- if user is not logged in -->
                            <a href="{% url 'login' %}" class="button mr-4">
                                <img src="../../static/images/ic_login_24dp.svg" class="desktop-hidden" />
                                <span class="mobile-hidden">Anmelden</span>
                            </a>
                            <a href="{% url 'register' %}" class="button mr-4">
                                <img src="../../static/images/ic_person_add_24dp.svg" class="desktop-hidden" />
                                <span class="mobile-hidden">Registrieren</span>
                            </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>

        {% block index %}
        {% endblock %}

        <div class="container pt-8">
            <!-- Dashboard -->
            {% block dashboard %}
            {% endblock %}

            <!-- Subjects -->
            {% block subjects_index %}
            {% endblock %}
            {% block subjects_create %}
            {% endblock %}
        
            <!-- Symbols -->
            {% block icons_index %}
            {% endblock %}
            {% block icons_create %}
            {% endblock %}
        </div>

        <div style="background: var(--md-sys-color-tertiary-container)" class="pb-4 pt-4">
            <div class="container pt-4">
                <button id="DarkModeButton" class="button" onclick="ToggleDarkMode()">Dark mode</button>
                <button id="LightModeButton" class="button" onclick="ToggleLightMode()">Light mode</button>
            </div>
            <div class="container pb-4">
                <button id="DefaultContrastButton" class="button" onclick="ToggleDefaultContrast()">Default contrast</button>
                <button id="MediumContrastButton" class="button" onclick="ToggleMediumContrast()">Medium contrast</button>
                <button id="HighContrastButton" class="button" onclick="ToggleHighContrast()">High contrast</button>
            </div>
        </div>
    </body>
</html>
<script src="{% static 'scripts/Cookies.js' %}"></script>
<script src="{% static 'scripts/ColorMode.js' %}"></script>

templates/notenanalyse/dashboard.html
{% extends 'notenanalyse/base.html' %}

{% block dashboard %}

    <div class="flex flex-wrap space-between">
        <!-- Hello user! -->
        <div class="w-75">
            {% if user.first_name %}
                <h1>Hallo {{ user.first_name }}!</h1>
            {% else %}
                <h1>Hallo {{ user.username }}!</h1>
            {% endif %}
            <h3>Deine Durchschnittsnote beträgt 1 (wip).</h3>

            <div class="flex flex-wrap align-center gap-4">
                <a href="{% url 'subjects' %}" class="outlined-button">
                    <div>
                        <div class="mt-4">
                            <img src="../../static/images/ic_blackboard_64px.png" alt="Blackboard" height="64" />
                        </div>
                        <div class="mb-4">
                            <b>Deine Fächer</b>
                        </div>
                    </div>
                </a>
                <a href="{% url 'index' %}" class="outlined-button">
                    <div>
                        <div class="mt-4">
                            <img src="../../static/images/ic_homework_64px.png" alt="School book" height="64" />
                        </div>
                        <div class="mb-4">
                            <b>Deine Noten</b>
                        </div>
                    </div>
                </a>
                <a href="{% url 'index' %}" class="outlined-button">
                    <div>
                        <div class="mt-4">
                            <img src="../../static/images/ic_bar-chart_64px.png" alt="Bar chart" height="64" />
                        </div>
                        <div class="mb-4">
                            <b>Analysieren</b>
                        </div>
                    </div>
                </a>
                <a href="{% url 'account:me' %}" class="outlined-button">
                    <div>
                        <div class="mt-4">
                            <img src="../../static/images/ic_user_64px.png" alt="Account" height="64" />
                        </div>
                        <div class="mb-4">
                            <b>Dein Konto</b>
                        </div>
                    </div>
                </a>
            </div>
        </div>

    <!-- Charts -->
    <div class="w-25">
        <div>
            <h3>Deine Flop-3-Fächer</h3>
            <p>Gib' nicht auf! Lern' weiter, dann schaffst du bessere Noten!</p>
        </div>
        <div class="mt-4">
            <h3>Deine Top-3-Fächer</h3>
        </div>
    </div>
    </div>

{% endblock dashboard %}

templates/notenanalyse/index.html
{% extends 'notenanalyse/base.html' %}

{% block index %}
<div style="height: 85%; background: var(--md-sys-color-primary); color: var(--md-sys-color-on-primary); margin-top: -12px">
    <div class="container">
        <h1 class="pt-4" style="color: var(--md-sys-color-on-primary)">
            Schulnotenanalyse
        </h1>
        <h3 style="color: var(--md-sys-color-on-primary)">
            Dein Tool zum Verwalten deiner Klausurenergebnisse.
        </h3>
        <div>
            <div>
                <a href="{% url 'register' %}" style="width: 25rem" class="button">🚀 Jetzt durchstarten!</a>
            </div>
            <div class="mt-2 pb-4">
                <a href="{% url 'login' %}" style="width: 25rem" class="outlined-button">🧑‍💻 Ich habe schon einen Account</a>
            </div>
            <div class="mt-4"></div>
        </div>
    </div>
</div>

<div class="container mb-4">
    <div class="flex flex-wrap space-between align-center">
        <img style="background: url('../../static/images/pexels-anastasiya-gepp-654466-1462630.jpg') center;height: 25rem; background-size: cover; width: 25rem; border-radius: 12.5rem">
        <div style="width: calc(95% - 25rem)">
            <h3>Deine Klausuren, dein Durchschnitt</h3>
            <p>Verwende die Schulnotenanalyse für die Ausrechnung deines Notenschnitts - auch für jedes einzenlnde Fach.</p>
            <p>Analysiere deine Top-3- und Flop-3-Fächer, damit du genau weißt, wofür du noch lernen musst! Mit der Schulnotenanalyse behälst du immer den Überblick über deine Fächer!</p>
        </div>
    </div>
</div>

<div style="background: var(--md-sys-color-secondary-container);">
    <div class="container pb-8 pt-8">
    <div class="flex flex-wrap space-between align-center pt-8 pb-8">
        <div style="width: calc(95% - 25rem)">
            <h3 style="color: var(--md-sys-color-on-secondary-container)">Übersichtlich und strukturiert</h3>
            <p style="color: var(--md-sys-color-on-secondary-container)">Schüler lieben es, die Schulnotenanalyse zu verwenden, da die Benutzeroberfläche, einfach, einheitlich und klar strukturiert gestaltet ist.</p>
            <p style="color: var(--md-sys-color-on-secondary-container)">Mithilfe des selbsterklärendem Dashboards lassen sich die relevantesten Informationen sofort einsehen.</p>
        </div>
        <img style="background: url('../../static/images/pexels-buro-millennial-636760-1438081.jpg') center;height: 25rem; background-size: cover; width: 25rem; border-radius: 12.55rem">
    </div>
</div>
{%  endblock %}

templates/notenanalyse/login.html
{% extends 'account/base.html' %}

{% block authForm %}

    <h1>Anmelden</h1>
    <h3>Melde dich an, damit du deinen Account nutzen kannst!</h3>

    <form method="post" action="" class="pt-8">
        {% csrf_token %}
        {{ L_Form.as_p }}
        <button type="submit">Login</button>
    </form>
    <a href="{% url 'register' %}" class="outlined-button" style="margin-left: 2px; margin-top: 1rem">Ich habe noch keinen Account!</a>
{% endblock authForm %}

templates/notenanalyse/register.html
{% extends 'account/base.html' %}

{% block authForm %}
    <h1>Registrieren</h1>
    <h3>Wähle deine Anmeldedaten, mit denne du dich hier anmelden kannst!</h3>

    <form method="post" action="">
        {% csrf_token %}
        {{ R_Form.as_p }}
        <button type="submit">Registrieren</button>
    </form>
    <a href="{% url 'login' %}" class="outlined-button" style="margin-left: 2px; margin-top: 1rem">Ich habe schon einen Account!</a>
{% endblock authForm %}